server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net:3306/heroku_c875f538e734af0
    username: b3cbdaeb0bc884
    password: 1dcaa063
    driver-class-name: com.mysql.jdbc.Driver